# Wstęp {-}

```{=latex}
\fancyhead[LO]{\textbf{\small{Wstęp}}}
\renewcommand{\headrulewidth}{0.5pt}
```

Analiza danych funkcjonalnych to nowoczesny dział statystyki matematycznej zajmujący się danymi reprezentowanymi przez funkcje określone na pewnym zbiorze domkniętym. Jej metody znajdują zastosowanie w wielu praktycznych zagadnieniach, w szczególności w medycynie, meteorologii, ekonomii, chemometrii. W pracy zostanie podjęta tematyka analizy powtarzanych pomiarów, które są danymi funkcjonalnymi. Omówione zostaną różne testy statystyczne dla problemu dwóch prób zależnych.

Praca składa się z następujących rozdziałów:

- **Rozdział 1**: opisanie problemu dwóch prób zależnych dla danych funkcjonalnych oraz przedstawienie odpowiedniej statystyki testowej,
- **Rozdział 2**: przedstawienie różnych metod prowadzących do postaci czterech testów statystycznych,
- **Rozdział 3**: przeprowadzenie symulacji mających na celu porównanie skończenie próbkowych własności przedstawionych testów statystycznych, tj. kontroli błędu pierwszego rodzaju i mocy testu,
- **Rozdział 4**: zastosowanie przedstawionych testów statystycznych do rzeczywistych danych.

Pisząc niniejszą pracę wykorzystano literaturę podaną w bibliografii. Jest ona podstawowym źródłem rozszerzającym informacje na tematy tu poruszane. Numeracja definicji, twierdzeń oraz przykładów jest oddzielna dla każdego rozdziału. Pierwsza cyfra oznacza numer rozdziału, a druga to kolejny numer twierdzenia, przykładu, itp. Analogicznie numerowane są wzory. Dowody kończą się symbolem $\blacksquare$.
