# Testy statystyczne

```{=latex}
\fancyhead[LO]{\textbf{\small{Testy statystyczne}}}
\renewcommand{\headrulewidth}{0.5pt}
```

## Test asymptotyczny

W podejściu asymptotycznym przedstawionym w \cite{MCC} formułuje się następujące twierdzenie:
\begin{tw}
Niech \(X_i(t) = m(t)+\epsilon_i(t), 1\le i\le n\) będą $n$ niezależnymi trajektoriami pochodzących z procesów $L^2$ definiowanych na przedziale $[0,2]$, z wartością oczekiwaną  $\bigwedge_{t\in[0,2]}\doubleE[\epsilon_i(t)]=0$ oraz funkcją kowariancji $\doubleC(s,t)$.
Wówczas przy prawdziwości hipotezy zerowej $\bigwedge_{t\in[0,1]}m(t)=m(1+t)$ zachodzi
\[
\scriptC_n \xto{d}n\sum_{k\in\doubleN} \lambda_kA_k,
\]
gdzie $A_k$ \AAA{czym to wszystko jest? Central $\chi^2$ distribution?}
\end{tw}
\begin{proof}

\end{proof}

## Testy bootstrapowe i permutacyjne

Założenie addytywności przedstawione w równaniu \ref{eqn:addytywnosc} jest niewłaściwe dla wielu różnych funkcji, w szczególności gęstości -- muszą one spełniać konkretne warunki \AAA{[definicja gęstości?]}. W związku z tym w \cite{MCC} przedstawia się dwa podejścia nieparametryczne, niewymagające wyżej wspomnianego założenia o addytywności.

Przy prawdziwości hipotezy zerowej spełniona jest równość
\begin{equation}
\label{eqn:c_h0}
\scriptC_n = n\int_0^1 (\bar{X}(t) - m(t) + m(1+t) - \bar{X}(1+t))^2 dt.
\end{equation}
Do powyższej statystyki można wykorzystać **metodę bootstrapową** w oparciu o następujące kroki:

1. Obliczyć $\scriptC_n$ na podstawie ustalonego podziału $\tau$ zbioru $[0,1]$.
2. Wybrać $B$ niezależnych prób bootstrapowych \AAA{nie skończyłem}
3. Wykorzystując \AAA{coś}, obliczyć wartości
4. Rozkład $\scriptC_n$ szacuje się na podstawie...

\begin{tw}
\AAA{zbieżność do tego czegoś}
\end{tw}
\begin{proof}

\end{proof}

## Test oparty o przybliżenie Boxa

W \cite{Smaga} zwrócono uwagę na problem wyżej opisanych metod, jakim jest ich czasochłonność. W celu znalezienia szybszego spodobu przybliżenia rozkładu $\scriptC_n$ wykorzystano tam przybliżenie Boxa przy założeniu hipotezy zerowej.

\AAA{czy tu ma być cały proces badawczy z \cite{Smaga} przepisany?}