# Podsumowanie {-}

```{=latex}
\fancyhead[LO]{\textbf{\small{Podsumowanie}}}
\renewcommand{\headrulewidth}{0.5pt}
```

Tematem pracy jest przedstawienie różnych technik weryfikacji hipotezy o równości dwóch prób zależnych dla danych funkcjonalnych. Problem ten, jak i wiele innych zagadnień związanych z analizą danych funkcjonalnych, został poruszony w licznych pracach naukowych oraz monografiach. Prace \cite{MCC} oraz \cite{Smaga}, będące głównym źródłem przedstawionych tu informacji, opisują narzędzia służące do weryfikacji wspomnianej hipotezy, w&nbsp;szczególności statystykę testową pozwalającą na kwantyfikację różnic pomiędzy dwoma próbami. Statystyka ta, zainspirowana badaniem różnic pomiędzy grupami na styl metod analizy wariancji ANOVA, jest całką kwadratu różnicy pomiędzy funkcjami średnimi poszczególnych procesów.

Rozkład owej statystyki testowej przy założeniu hipotezy zerowej może zostać oszacowany na różne sposoby. Pierwszym z nich jest metoda asymptotyczna, w ramach której $p$-wartość testu statystycznego oblicza się, korzystając z procesów gaussowskich i&nbsp;obliczając wartości statystyki testowej dla tychże. Metoda asymptotyczna jest metodą niewymagającą względnie dużej mocy obliczeniowej, jednak założenie addytywności wynikającej z modelu danych (patrz równanie \eqref{eqn:addytywnosc}) często nie jest spełnione, między innymi dla funkcji gęstości. W tym celu opracowane zostały podejścia nieparametryczne, korzystające z metody bootstrapowej oraz permutacyjnej, nie wymagające wspomnianego założenia. W odróżnieniu od metody asymptotycznej, dla tych metod generuje się procesy przy pomocy danych oryginalnych, losując rekordy i budując z nich pomocnicze dane, dla których obliczane są wartości statystyki testowej. Wreszcie metoda oparta o&nbsp;przybliżenie Boxa, zaproponowana w pracy \cite{Smaga}, ma na celu dodatkowe przyspieszenie obliczeń przy jednoczesnym zachowaniu własności testu i z tego powodu korzysta z&nbsp;kumulant -- wielkości często stosowanych w analizie danych funkcjonalnych. Z ich pomocą przybliża się rozkład badanej statystyki testowej za pomocą rozkładu $\chi^2$, modyfikowanego przez stałe oparte na parametrach próby. Metoda ta osiąga postawiony cel przyspieszenia obliczeń, będąc najszybszą spośród przedstawionych.

Na poparcie poprawności zastosowania wyżej wymienionych technik przeprowadzone zostały badania symulacyjne w celu oszacowania skończenie próbkowych własności testów, tzn. jego rozmiaru i mocy. W ramach symulacji skonstruowano osiem modeli i do danych wygenerowanych na ich podstawie zastosowano rozpatrywane testy. Dla zapewnienia dokładności oszacowań symulacje wielokrotnie powtarzano, a wyniki zostały uśrednione. Uzyskane w ten sposób rozmiary oraz moce testów okazały się spełniać wymogi teoretyczne, opisane przez odpowiednie przedziały ufności -- wobec tego omawiane procedury w poprawny sposób są w stanie opisywać różnice pomiędzy danymi funkcjonalnymi w problemie dwóch prób zależnych.

Omawiane testy statystyczne zostały zastosowane także do rzeczywistych danych, jakimi są dane pochodzące z badań dotyczących momentu siły różnych typów ortez. Po obliczeniu odpowiednich $p$-wartości, wszystkie metody poprawnie identyfikują różnice pomiędzy całością rozpatrywanych danych oraz tożsamość funkcji średnich procesów w&nbsp;ich skróconej wersji.

Analiza danych funkcjonalnych, będąc stosunkowo nowo powstałą dziedziną statystyki matematycznej, posiada wiele narzędzi do rozwiązywania problemów analogicznych do tych znajdowanych w podejściu klasycznym. Niemalejące zainteresowanie dziedziną i tempo współczesnego świata sprawiają, że wiedza na temat danych funkcjonalnych będzie się z pewnością dalej poszerzać i odpowiadać na coraz trudniejsze zagadnienia.